### ISSUE TITLE
Nextcloud 30 support

### ISSUE THREAD

**Issue by IndrekHaav** [nextcloud/health#200]
### Is your feature request related to a problem? Please describe.

Nextcloud 30 has been released, but this app doesn't currently support it.

### Describe the solution you'd like

Please add support for Nextcloud 30.

**Comment by TheRealRWJ** [comment]
Yes, please.

**Comment by Shorty365** [comment]
Would like support for Nextcloud 30 too. This is, for me, the only app that holds me from upgrding to NC 30.

**Comment by NuclearPhoenixx** [comment]
I can report that the app works with NC 30. It will get automatically disable with the update, so you'll have to manually re-enable it, but after that it works just fine (at least for me, YMMV of course). It would be nice to have official NC 30 support, though.

**Comment by Shorty365** [comment]
Tried the upgrade to NC30 and after re-enabling I can confirm that the Health App works. Still an official upgrade of the app would be nice. @NuclearPhoenixx Thanks for your hint!

**Comment by IndrekHaav** [comment]
Thanks @NuclearPhoenixx  and @Shorty365, I tested on NC 30 as well and can also confirm the app seems to work fine. I submitted a PR to bump the max supported version, hopefully it can get merged.

**Comment by Benedikt81** [comment]
This issue isn't completed as the new version of the app isn't released and published yet.

**Comment by ssarna1** [comment]
App is marked as incompatible with 30.0.4.

**Comment by IndrekHaav** [comment]
Yes, the PR got merged but there's no new release yet. See the #216 for reasons why. Unfortunately I cannot re-open the issue to signify that it's still unresolved.

**Comment by ssarna1** [comment]
Thanks for the update. I can't wrap my head around the fact, that the official nextcloud app has no maintainer...

**Comment by IndrekHaav** [comment]
Everyone, please see the update in the README, the app is now officially deprecated:

https://github.com/nextcloud/health?tab=readme-ov-file#farewell-to-the-nextcloud-health-app-

@datenangebot Thank you for your work on developing and maintaining the app so far.
